#!/usr/bin/env python3
"""Generate libmscore/ms4tables.h: MuseScore 4.7.5's playback data for the MS4 note model
(libmscore/ms4playback.*). Run with a MuseScore 4 source tree:

    python3 tools/ms4playback/gen_tables.py <MuseScore 4 source root>

Sources:
  src/framework/mpe/resources/general_*_articulations_profile.json
      per family: each articulation's durationFactor, timestampOffset, 11-point dynamic curve,
      and (bends) 11-point pitch curve
  src/framework/mpe/mpetypes.h                            ArticulationType enum order
  src/engraving/playback/mapping/*setupdataresolver.cpp   instrument id -> family
  share/instruments/instruments.xml (this tree)           instrument groups, for ids MS4 does not list
"""
import json, os, re, sys
import xml.etree.ElementTree as ET
from collections import Counter, defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
MS4 = os.path.join(sys.argv[1], 'src')
MPE = os.path.join(MS4, 'framework', 'mpe')

FAMS = ['Strings', 'Winds', 'Keyboards', 'Voices', 'Percussions']
FILE = {'Strings': 'strings', 'Winds': 'winds', 'Keyboards': 'keyboard', 'Voices': 'voice', 'Percussions': 'percussion'}
JSON_TO_ENUM = {'SulPonticello': 'SulPont', 'ShortTrill': 'UpperMordent', 'Mordent': 'LowerMordent'}
BENT = ['Fall', 'QuickFall', 'Doit', 'Plop', 'Scoop', 'BrassBend']


def enum_order():
    src = open(os.path.join(MPE, 'mpetypes.h')).read()
    body = re.search(r'enum class ArticulationType : signed char \{(.*?)\};', src, re.S).group(1)
    names = [re.sub(r'\s*=.*', '', x.strip()) for x in re.sub(r'//[^\n]*', '', body).split(',')]
    return [n for n in names if n and n not in ('Undefined', 'Last')]


def profiles(order):
    prof, pitch = {}, {}
    for fam in FAMS:
        d = json.load(open(os.path.join(MPE, 'resources', 'general_%s_articulations_profile.json' % FILE[fam])))
        for key, segs in d['patterns'].items():
            name = JSON_TO_ENUM.get(key, key)
            if name not in order:
                continue
            seg = [s for s in segs if s['patternPosition'] == 0][0]      # a note fully inside the articulation
            a = seg['arrangementPattern']
            offs = sorted(seg['expressionPattern']['dynamicOffsets'], key=lambda p: p['offsetPosition'])
            assert [p['offsetPosition'] for p in offs] == list(range(0, 10001, 1000)), (fam, key)
            prof[(fam, name)] = (a['durationFactor'], a['timestampOffset'], [p['offsetValue'] for p in offs])
            if name in BENT:
                pofs = sorted(seg['pitchPattern']['pitchOffsets'], key=lambda p: p['offsetPosition'])
                pitch[(fam, name)] = [p['offsetValue'] for p in pofs]
    return prof, pitch


def ms4_families():
    fam = {}
    mp = os.path.join(MS4, 'engraving', 'playback', 'mapping')
    for f in sorted(os.listdir(mp)):
        if f.endswith('setupdataresolver.cpp'):
            src = open(os.path.join(mp, f)).read()
            for iid, cat in re.findall(r'\{\s*"([\w.-]+)",\s*\{\s*SoundId::\w+,\s*SoundCategory::(\w+)', src):
                fam.setdefault(iid, cat)
    return fam


GROUP_FAMILY = {'woodwinds': 'Winds', 'brass': 'Winds', 'strings': 'Strings', 'plucked-strings': 'Strings',
                'keyboards': 'Keyboards', 'vocals': 'Voices', 'pitched-percussion': 'Percussions',
                'unpitched-percussion': 'Percussions', 'electronic-instruments': 'Keyboards',
                'marching': 'Percussions'}


def family_by_musicxml(fam4):
    """Instrument::instrumentId() in MuseScore 3 is the MusicXML sound id; several templates share
    one, so the family is a majority vote over the templates with that id."""
    root = ET.parse(os.path.join(ROOT, 'share', 'instruments', 'instruments.xml')).getroot()
    votes = defaultdict(Counter)
    for g in root.iter('InstrumentGroup'):
        for ins in g.iter('Instrument'):
            iid = ins.get('id')
            f = fam4.get(iid) or GROUP_FAMILY.get(g.get('id'))
            if not f:                                 # early music / world: by name
                fn = (ins.findtext('family') or '') + iid
                f = ('Winds' if re.search(r'flute|reed|horn|trumpet|cornett|sackbut|recorder|bagpipe|shawm|oboe|bassoon|clarinet|crumhorn', fn)
                     else 'Strings' if re.search(r'viol|lute|guitar|harp|zither|oud|sitar|banjo|mandolin|string|koto|shamisen|erhu|balalaika', fn)
                     else 'Percussions' if re.search(r'drum|percussion|bell|gong|cymbal', fn) else 'Keyboards')
            mx = ins.findtext('musicXMLid')
            if mx:
                votes[mx][f] += 1
    return {mx: c.most_common(1)[0][0] for mx, c in votes.items()}


def main():
    order = enum_order()
    prof, pitch = profiles(order)
    fam = family_by_musicxml(ms4_families())
    L = ['// Generated by tools/ms4playback/gen_tables.py from MuseScore 4.7.5 — do not edit.',
         '// The playback data of MS4\'s note model (see ms4playback.h). Units: 10000 = 100 %;',
         '// dynamic 5000 = "natural"; pitch 50 = one semitone.',
         '', '#ifndef __MS4TABLES_H__', '#define __MS4TABLES_H__', '', 'namespace Ms {', 'namespace Ms4 {', '',
         '// ArticulationType, in MS4\'s enum order (the order its std::map walks them in)',
         'enum class Art : signed char {']
    L += ['      %s,' % n for n in order]
    L += ['      COUNT', '      };', '',
          'static const char* const ART_NAMES[] = {']
    L += ['      "%s",' % n for n in order]
    L += ['      };', '',
          'enum class Family : signed char { %s };' % ', '.join(FAMS), '',
          'struct Pattern { int dur; int ts; int curve[11]; };',
          'struct ProfileEntry { Family family; Art art; Pattern p; };',
          'static const ProfileEntry PROFILE[] = {']
    for (f, n), (d, t, c) in sorted(prof.items(), key=lambda kv: (FAMS.index(kv[0][0]), order.index(kv[0][1]))):
        L.append('      { Family::%s, Art::%s, { %d, %d, { %s } } },' % (f, n, d, t, ', '.join(map(str, c))))
    L += ['      };', '', 'struct PitchEntry { Family family; Art art; int curve[11]; };', 'static const PitchEntry PITCH[] = {']
    for (f, n), c in sorted(pitch.items(), key=lambda kv: (FAMS.index(kv[0][0]), order.index(kv[0][1]))):
        L.append('      { Family::%s, Art::%s, { %s } },' % (f, n, ', '.join(map(str, c))))
    L += ['      };', '', '// MusicXML sound id (Instrument::instrumentId()) -> family',
          'struct FamilyEntry { const char* id; Family family; };', 'static const FamilyEntry FAMILY[] = {']
    L += ['      { "%s", Family::%s },' % (k, fam[k]) for k in sorted(fam)]
    L += ['      };', '', '} // namespace Ms4', '} // namespace Ms', '#endif', '']
    out = os.path.join(ROOT, 'libmscore', 'ms4tables.h')
    open(out, 'w').write('\n'.join(L))
    print('%s: %d articulation types, %d profile entries, %d bends, %d sound ids'
          % (out, len(order), len(prof), len(pitch), len(fam)))


main()
