#!/usr/bin/env python3
"""gen_tuning_tables.py <table.js> <tuning.qml>  >  libmscore/tuningtables.h

The data of the fork's tuning (libmscore/tuning.cpp), taken from the two plugins it builds in, so
that the fork and the plugins play the same pitches:

  table.js    the Microtonal Tuner plugin's accidental table (cents from the natural per
              accidental, generated there from MuseScore 3.6.2's accidental.cpp), with the
              AccidentalType name of each entry (ACC_NAMES)
  tuning.qml  billhails' Tuning plugin (github.com/billhails/MuseScore-plugins, src/Tuning/3.x):
              its 17 temperaments, 12 offsets each in the order of the circle of fifths from the
              root (C G D A E B F# C# G# Eb Bb F when the root is C), plus root and pure tone

Symbols with no value (null in table.js) are left out: tuning.cpp treats them as "no value"."""
import json, re, sys


def js_array(text, name):
    m = re.search(r'var %s = (\[.*?\]);' % name, text, re.S)
    body = re.sub(r'//[^\n]*', '', m.group(1))
    return json.loads(body)


def main():
    table = open(sys.argv[1]).read()
    acc = js_array(table, 'ACC')
    names = js_array(table, 'ACC_NAMES')
    assert len(acc) == len(names), (len(acc), len(names))

    qml = open(sys.argv[2]).read()
    temps = []
    for m in re.finditer(r"property var (\w+): \{\s*'offsets': \[([^\]]*)\],\s*'root': (\d+),\s*'pure': (\d+),\s*"
                         r"'name': \"(\w+)\"", qml):
        offsets = [float(x) for x in m.group(2).split(',')]
        assert len(offsets) == 12
        temps.append((m.group(5), offsets, int(m.group(3)), int(m.group(4))))
    assert len(temps) == 17, len(temps)

    out = ['// Generated by tools/tuning/gen_tuning_tables.py from the Microtonal Tuner plugin\'s table.js',
           '// and billhails\' Tuning plugin (tuning.qml). Do not edit by hand.',
           '',
           '#ifndef __TUNINGTABLES_H__',
           '#define __TUNINGTABLES_H__',
           '',
           'namespace Ms {',
           'namespace TuningTables {',
           '',
           'struct AccCents { AccidentalType type; SymId sym; double cents; };',
           '',
           '// cents from the natural note, as MuseScore 3.6.2 gives them; symbols without a value are absent',
           'static const AccCents accidentals[] = {']
    valued = 0
    for entry, name in zip(acc, names):
        if entry is None or name == 'NONE':
            continue
        cents, sym = entry
        out.append('      { AccidentalType::%s, SymId::%s, %s },' % (name, sym, repr(float(cents))))
        valued += 1
    out += ['      };', '',
            'struct Preset { const char* name; double offsets[12]; int root; int pure; };', '',
            '// offsets in cents from equal temperament, along the circle of fifths from the root',
            'static const Preset temperaments[] = {']
    for name, offsets, root, pure in temps:
        out.append('      { "%s", { %s }, %d, %d },' % (name, ', '.join(repr(x) for x in offsets), root, pure))
    out += ['      };', '', '} // namespace TuningTables', '} // namespace Ms', '#endif', '']
    sys.stdout.write('\n'.join(out))
    sys.stderr.write('%d valued accidentals, %d temperaments\n' % (valued, len(temps)))


if __name__ == '__main__':
    main()
