//=============================================================================
//  MuseScore
//  Music Composition & Notation
//
//  Ms4: MuseScore 4.7.5's note model, for playback that sounds as in MuseScore 4
//  through its FluidSynth back end. What MS4 does to a note before its synth plays it:
//
//    the articulations it gets from its context (slur, symbols, tremolo, noteheads,
//    playing technique, sf-type dynamics)                 engraving/playback/metaparsers
//    their averaged length/offset/dynamic pattern          mpe ArticulationMap
//    the note's expression curve and velocity              mpe NoteEvent, FluidSequencer
//    the dynamic level in force (markings, hairpins)       engraving/playback/playbackcontext
//
//  Quirks of the original are kept: the goal is to sound like MS4, not to improve on it.
//  Data: ms4tables.h (generated by tools/ms4playback/gen_tables.py).
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License version 3.
//=============================================================================

#ifndef __MS4PLAYBACK_H__
#define __MS4PLAYBACK_H__

#include <map>
#include <vector>

#include "ms4tables.h"

namespace Ms {

class Chord;
class Dynamic;
class Hairpin;
class Instrument;
class Note;
class Part;
class Score;

namespace Ms4 {

constexpr int HUNDRED = 10000;
constexpr int NATURAL = 5000;             // DynamicType::Natural
constexpr int STEP = 500;                 // DYNAMIC_LEVEL_STEP (5 %)

struct ArtRef {
      Art art;
      bool fallback;                      // SymbolsMetaParser: use Standard's pattern if the family lacks one
      };

struct NoteResult {
      int dur { HUNDRED };                // length factor, 10000 = 100 %
      int ts { 0 };                       // on-time offset, 10000 = the note's duration
      int velocity { 64 };                // 7-bit note-on velocity, as FluidSequencer sends it
      std::vector<Art> arts;              // the resolved types, MS4 enum order
      };

Family family(const Instrument* instrument);
int expressionLevel(int level);           // FluidSequencer::expressionLevel: MS4 level -> CC11 / velocity
NoteResult note(Family family, const std::vector<ArtRef>& arts, int dynamicLevel, bool snd);

//---------------------------------------------------------
//   Dynamics
//    PlaybackContext's dynamics map for one part: tick -> MS4 dynamic level, built from the
//    dynamic markings and hairpins as MS4 does (one map for all voices of the part: an MS3
//    dynamic applies to the whole instrument, like MS4's default voice assignment)
//---------------------------------------------------------

class Dynamics {
      std::map<int, int> _levels;

      void apply(int tick, int level) { _levels[tick] = level; }
      int appliable(int tick) const;
      int nominal(int tick) const;
      void addDynamic(Score*, Dynamic*);
      void addHairpin(Score*, Hairpin*);

   public:
      void build(Score* score, Part* part);
      int levelAt(int tick) const { return appliable(tick); }
      const std::map<int, int>& levels() const { return _levels; }
      bool subitoAt(int tick) const { return _subito.count(tick); }

   private:
      std::map<int, bool> _subito;        // ticks with an sf-type dynamic (AnnotationsMetaParser: Subito)
      };

//---------------------------------------------------------
//   Context
//    what the renderer keeps per part while rendering a score
//---------------------------------------------------------

struct PartContext {
      Family family { Family::Keyboards };
      bool snd { false };
      Dynamics dynamics;
      };

std::vector<ArtRef> chordArticulations(const Chord* chord, const Dynamics& dynamics);
std::vector<ArtRef> noteArticulations(const Note* note, const std::vector<ArtRef>& chordArts);

} // namespace Ms4
} // namespace Ms
#endif
