//=============================================================================
//  MuseScore
//  Music Composition & Notation
//
//  Ms4: MuseScore 4.7.5's note model, for playback that sounds as in MuseScore 4
//  through its FluidSynth back end. What MS4 does to a note before its synth plays it:
//
//    the articulations it gets from its context (slur, symbols, tremolo, noteheads,
//    playing technique, sf-type dynamics)                 engraving/playback/metaparsers
//    their averaged length/offset/dynamic pattern          mpe ArticulationMap
//    the note's expression curve and velocity              mpe NoteEvent, FluidSequencer
//    the dynamic level in force (markings, hairpins)       engraving/playback/playbackcontext
//
//  Quirks of the original are kept: the goal is to sound like MS4, not to improve on it.
//  Data: ms4tables.h (generated by tools/ms4playback/gen_tables.py).
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License version 3.
//=============================================================================

#ifndef __MS4PLAYBACK_H__
#define __MS4PLAYBACK_H__

#include <map>
#include <set>
#include <vector>

#include "ms4tables.h"

namespace Ms {

class Chord;
class Dynamic;
class Element;
class Hairpin;
class Instrument;
class Note;
class Part;
class Score;
class Spanner;
class StaffTextBase;

namespace Ms4 {

constexpr int HUNDRED = 10000;
constexpr int NATURAL = 5000;             // DynamicType::Natural
constexpr int STEP = 500;                 // DYNAMIC_LEVEL_STEP (5 %)

struct ArtRef {
      Art art;
      bool fallback;                      // SymbolsMetaParser: use Standard's pattern if the family lacks one
      int phase { 0 };                    // 0 chord (ChordArticulationsParser), 1 note (NoteArticulationsParser),
                                          // 2 merged from a tied note (addTiedNote)
      bool erased { false };              // taken out after its phase (the principal's grace type)
      int pitchRange { 0 };               // overallPitchChangesRange (a glissando's interval, 50 = semitone)
      };

// ArticulationMap is a std::unordered_map: where MS4 takes "the first" articulation (the average's
// fallback, the technique's channel, the renderer of a chord) it takes the map's iteration order. The
// same map built the same way gives the same order (with the same standard library as MS4's build).
// Articulations without a pattern in the family (fam >= 0) never enter the map.
std::vector<Art> iterationOrder(const std::vector<ArtRef>& arts, int fam = -1);

struct NoteResult {
      int dur { HUNDRED };                // length factor, 10000 = 100 %
      int ts { 0 };                       // on-time offset, 10000 = the note's duration
      int velocity { 64 };                // 7-bit note-on velocity, as FluidSequencer sends it
      std::vector<Art> arts;              // the resolved types, MS4 enum order
      bool bend { false };                // FluidSequencer plays a pitch curve (BEND_SUPPORTED_TYPES)
      int pitchCurve[11] = {};            // at 0, 10 … 100 % of the note; 50 = one semitone
      };

int pitchBendLevel(int pitchLevel);       // FluidSequencer::pitchBendLevel: 14-bit wheel, 24 semitones

Family family(const Instrument* instrument);
int expressionLevel(int level);           // FluidSequencer::expressionLevel: MS4 level -> CC11 / velocity
NoteResult note(Family family, const std::vector<ArtRef>& arts, int dynamicLevel, bool snd);

//---------------------------------------------------------
//   Dynamics
//    PlaybackContext's dynamics map for one part: tick -> MS4 dynamic level, built from the
//    dynamic markings and hairpins as MS4 does (one map for all voices of the part: an MS3
//    dynamic applies to the whole instrument, like MS4's default voice assignment)
//---------------------------------------------------------

class Dynamics {
      // per track (PlaybackContext::m_dynamicsByTrack): tick -> level and the priority of the
      // voice assignment that set it
      struct Info { int level; int priority; };
      std::map<int, std::map<int, Info>> _byTrack;
      int _strack { 0 };
      int _etrack { 0 };
      std::map<int, int> _merged;

      void apply(const Element* e, int tick, int level);
      int appliable(int track, int tick) const;
      int nominal(int track, int tick) const;
      void addDynamic(Score*, Dynamic*, int offset);
      void addHairpin(Score*, Hairpin*, int offset);
      void addTechnique(const StaffTextBase* text, int utick);
      void mergeTracks();

   public:
      void build(Score* score, Part* part);
      int levelAt(int track, int utick) const { return appliable(track, utick); }   // unrolled tick
      const std::map<int, int>& levels() const { return _merged; }     // all tracks' changes (FluidSequencer::updateDynamicEvents)
      bool subitoAt(int tick, int staffIdx) const { return _subito.count({ staffIdx, tick }) > 0; }
      int spannerStop(const Spanner* sp) const;     // tick2, clipped as MS4's collision-free intervals
      Art techniqueAt(int utick) const;             // the playing technique in force (COUNT: none / natural)

   private:
      std::set<std::pair<int, int>> _subito;      // (staff, tick) of an sf-type dynamic (AnnotationsMetaParser: Subito)
      std::map<const Spanner*, int> _clippedStop;
      std::map<int, Art> _techniques;             // PlaybackContext::m_playTechniquesMap, at unrolled ticks
      };

//---------------------------------------------------------
//   Sounds
//    MS4 picks an instrument's preset itself (soundmapping.h), ignoring the score's program,
//    and switches preset per note for some playing techniques. Here an instrument's MuseScore 3
//    channels serve as slots: the first plays MS4's standard preset, the others the technique
//    presets (a channel whose name fits first: "pizzicato" for Pizzicato …, then any free one).
//---------------------------------------------------------

struct Slot {
      int channel;                        // index into Instrument::channel()
      int bank;
      int program;
      };

struct Sounds {
      std::vector<Slot> channelSlots;            // one per channel of the instrument, slots[0] = standard
      std::vector<std::pair<Art, int>> artSlot;     // technique -> index into slots
      bool techniques { false };                   // MS4 maps playing techniques for the instrument
      int slotFor(const std::vector<Art>& noteArts) const;    // FluidSequencer's channel choice
      int layerFor(const std::vector<Art>& noteArts, int voice) const;
      };

Sounds sounds(const Instrument* instrument);

//---------------------------------------------------------
//   Context
//    what the renderer keeps per part while rendering a score
//---------------------------------------------------------

struct PartContext {
      Family family { Family::Keyboards };
      bool snd { false };
      Dynamics dynamics;
      std::map<const Instrument*, Sounds> sounds;
      };

//---------------------------------------------------------
//   OrnamentRule
//    OrnamentsRenderer's DISCLOSURE_RULES: sub-notes as steps to the diatonic neighbours
//    (+1 above, -1 below, 0 the note), a prefix, a body (repeated while it fits, for trills)
//    and a suffix; the sub-note length depends on the tempo
//---------------------------------------------------------

struct OrnamentRule {
      std::vector<int> prefix;
      bool repeat;
      std::vector<int> body;
      std::vector<int> suffix;
      float lowTempoTicks, mediumTempoTicks, highTempoTicks;
      float subNoteTicks(double bps) const;
      };

const OrnamentRule* ornamentRule(Art a);
int neighbourSemitones(const Note* note, int dir);      // chromaticPitchSteps for an automatic interval

std::vector<ArtRef> chordArticulations(const Chord* chord, const Dynamics& dynamics, int tickOffset = 0);
std::vector<ArtRef> noteArticulations(const Note* note, const std::vector<ArtRef>& chordArts);

} // namespace Ms4
} // namespace Ms
#endif
