//=============================================================================
//  MuseScore
//  Music Composition & Notation
//
//  Playability checker: W2 (woodwinds) / B1 (brass) register x dynamic rules.
//  GENERATED by tools/playability/gen_winds_dyn.py from tools/playability/w2b1_rules.py.
//  Do not edit by hand.
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License version 2
//  as published by the Free Software Foundation and appearing in
//  the file LICENCE.GPL
//=============================================================================

#ifndef __PLAYABILITYWINDSDYN_H__
#define __PLAYABILITYWINDSDYN_H__

#include <vector>

namespace Ms {

// the level a rule needs: any, pp or softer, exactly p or mp, fff or louder
enum class WindLevel { ANY, SOFT, P_MP, FFF };
// a mark (warning / red) with its row, or a note in the panel only
enum class WindDynKind { WARNING, RED, NOTE };

struct WindDynRule {
      const char* id;
      std::vector<const char*> instruments;  // playabilitywinds.h ids
      bool written;                          // lo/hi are written pitches (sounding - WindData::tr)
      int lo, hi;                            // MIDI, both ends included
      WindLevel level;
      WindDynKind kind;
      const char* text;
      const char* source;                    // book and page
      };

inline const std::vector<WindDynRule>& windDynRules()
      {
      static const std::vector<WindDynRule> rules = {
        { "W2-FL-HIGH", { "flute" }, false, 95, 98, WindLevel::SOFT, WindDynKind::WARNING,
          "flute B6-D7 is hard to play pp or softer",
          "Sevsay p. 75; Kennan & Grantham p. 76" },
        { "W2-OB-LOW-A", { "oboe" }, false, 58, 62, WindLevel::P_MP, WindDynKind::WARNING,
          "oboe Bb3-D4 is hard to play p or mp",
          "Blatter p. 100" },
        { "W2-OB-LOW-B", { "oboe" }, false, 58, 62, WindLevel::SOFT, WindDynKind::RED,
          "oboe Bb3-D4 cannot be played pp or softer",
          "Blatter p. 100, Ex. 3.34" },
        { "W2-OB-LOW-C", { "oboe" }, false, 63, 65, WindLevel::SOFT, WindDynKind::WARNING,
          "oboe Eb4-F4 is hard to play pp or softer",
          "Adler p. 195" },
        { "W2-OB-HIGH", { "oboe" }, false, 89, 93, WindLevel::FFF, WindDynKind::RED,
          "oboe F6-A6 cannot be played fff or louder",
          "Sevsay p. 78" },
        { "W2-BSN-LOW", { "bassoon" }, false, 34, 41, WindLevel::SOFT, WindDynKind::WARNING,
          "bassoon Bb1-F2 is hard to play pp or softer",
          "Adler p. 222" },
        { "W2-SAX-LOW-A", { "sopranino-saxophone", "soprano-saxophone", "alto-saxophone", "tenor-saxophone", "saxophone", "baritone-saxophone", "bass-saxophone" }, true, 58, 65, WindLevel::P_MP, WindDynKind::WARNING,
          "saxophone written Bb3-F4 is hard to play p or mp",
          "Blatter p. 127" },
        { "W2-SAX-LOW-B", { "sopranino-saxophone", "soprano-saxophone", "alto-saxophone", "tenor-saxophone", "saxophone", "baritone-saxophone", "bass-saxophone" }, true, 58, 65, WindLevel::SOFT, WindDynKind::RED,
          "saxophone written Bb3-F4 cannot be played pp or softer",
          "Blatter p. 127; Adler p. 218" },
        { "B1-HN-HIGH", { "horn" }, false, 74, 77, WindLevel::SOFT, WindDynKind::WARNING,
          "horn D5-F5 (written A5-C6) is hard to play pp or softer",
          "Sevsay p. 97; Kennan & Grantham p. 128" },
        { "B1-TPT-HIGH", { "trumpet", "bb-trumpet", "c-trumpet" }, true, 83, 86, WindLevel::SOFT, WindDynKind::RED,
          "trumpet written B5-D6 cannot be played pp or softer",
          "band Adler p. 332; Sevsay p. 120" },
        { "B1-TPT-LOW", { "trumpet", "bb-trumpet", "c-trumpet" }, true, 54, 59, WindLevel::SOFT, WindDynKind::WARNING,
          "trumpet written F#3-B3 is hard to play pp or softer",
          "Adler p. 332; Sevsay p. 102" },
        { "W2-FL-LOW", { "flute" }, false, 59, 71, WindLevel::ANY, WindDynKind::NOTE,
          "low flute: weak and easily covered; ff hardly possible",
          "Blatter p. 91; Sevsay p. 120" },
        { "W2-PIC-LOW", { "piccolo" }, false, 74, 88, WindLevel::ANY, WindDynKind::NOTE,
          "low piccolo: too weak to be heard in a tutti or heavy scoring",
          "Kennan & Grantham p. 79" },
        { "W2-AFL-LOW", { "alto-flute" }, false, 55, 65, WindLevel::ANY, WindDynKind::NOTE,
          "low alto flute: accompany it lightly",
          "Blatter p. 92" },
        { "W2-CL-HIGH", { "clarinet", "bb-clarinet", "a-clarinet" }, true, 93, 127, WindLevel::SOFT, WindDynKind::NOTE,
          "soft top clarinet (written A6 and up): the books disagree whether it works",
          "Sevsay p. 81 against Adler p. 206" },
        { "W2-ECL-TOP", { "eb-clarinet" }, false, 92, 96, WindLevel::ANY, WindDynKind::NOTE,
          "top Eb clarinet: dynamics may be limited; shrill when loud",
          "Adler p. 211; Blatter p. 110" },
        { "W2-BSN-TOP", { "bassoon" }, false, 68, 75, WindLevel::ANY, WindDynKind::NOTE,
          "high bassoon does not project: keep its accompaniment soft",
          "Adler p. 222" },
            };
      return rules;
      }

}     // namespace Ms
#endif
