//=============================================================================
//  MuseScore
//  Music Composition & Notation
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License version 2
//  as published by the Free Software Foundation and appearing in
//  the file LICENCE.GPL
//=============================================================================

// Generated by tools/playability/gen_brass.py from the owner's readings of Blatter's charts
// (Instrumentation and Orchestration, 2nd ed.: trombone pp. 469-470, valved brass pp. 463-464,
// horn pp. 461-462; kept outside this repository). Do not edit by hand.
// Entries in printed order, the first the standard one. Fundamentals: the highest on which every
// entry of the chart lies on a partial (see the script).

#ifndef __PLAYABILITYBRASS_H__
#define __PLAYABILITYBRASS_H__

#include <vector>

namespace Ms {
namespace Playability {

//---------------------------------------------------------
//   trombone slide positions, SOUNDING pitch, upward (alto and contrabass print no column between the
//   pedal tones and the 2nd partial). Positions as Blatter numbers them,
//   1-7; + 10 a raised (sharp) position. Sides: 0 no attachment, 1 F attachment, 2 E attachment.
//---------------------------------------------------------

enum class SlideChart : char { TENOR, ALTO, CONTRABASS };        // the tenor chart is the bass trombone's too

struct SlideRow {
      int pitch;
      bool pedal;                   // in the chart's pedal-tone bracket
      std::vector<int> side[3];
      };

inline const std::vector<SlideRow>& slideRows(SlideChart c)
      {
      static const std::vector<SlideRow> ROWS[3] = {
            // tenor
            {
                  { 27, true, { {}, { 3 }, { 2 } } },
                  { 28, true, { { 7 }, { 2 }, { 1 } } },
                  { 29, true, { { 6 }, { 1 }, {} } },
                  { 30, true, { { 5 }, {}, {} } },
                  { 31, true, { { 4 }, {}, {} } },
                  { 32, true, { { 3 }, {}, {} } },
                  { 33, true, { { 2 }, {}, {} } },
                  { 34, true, { { 1 }, {}, {} } },
                  { 35, false, { {}, {}, { 6 } } },
                  { 36, false, { {}, { 6 }, { 5 } } },
                  { 37, false, { {}, { 5 }, { 4 } } },
                  { 38, false, { {}, { 4 }, { 3 } } },
                  { 39, false, { {}, { 3 }, { 2 } } },
                  { 40, false, { { 7 }, { 2 }, { 1 } } },
                  { 41, false, { { 6 }, { 1 }, {} } },
                  { 42, false, { { 5 }, {}, { 6 } } },
                  { 43, false, { { 4 }, { 6 }, { 5 } } },
                  { 44, false, { { 3 }, { 5 }, { 4 } } },
                  { 45, false, { { 2 }, { 4 }, { 3 } } },
                  { 46, false, { { 1 }, { 3 }, { 2 } } },
                  { 47, false, { { 7 }, { 2 }, { 1, 6 } } },
                  { 48, false, { { 6 }, { 1, 6 }, { 5 } } },
                  { 49, false, { { 5 }, { 5 }, { 4 } } },
                  { 50, false, { { 4 }, { 4 }, { 3 } } },
                  { 51, false, { { 3 }, { 3 }, { 2, 6 } } },
                  { 52, false, { { 2, 7 }, { 2, 6 }, { 1, 5 } } },
                  { 53, false, { { 1, 6 }, { 1, 5 }, { 4 } } },
                  { 54, false, { { 5 }, { 4 }, { 3, 6 } } },
                  { 55, false, { { 4 }, { 3, 6 }, { 2, 5 } } },
                  { 56, false, { { 3, 7 }, { 2, 5 }, { 1, 4 } } },
                  { 57, false, { { 2, 6 }, { 1, 4 }, { 3, 16 } } },
                  { 58, false, { { 1, 5 }, { 3, 16 }, { 2, 15 } } },
                  { 59, false, { { 4, 7 }, { 2, 15 }, { 1, 6, 14 } } },
                  { 60, false, { { 3, 6 }, { 1, 6, 14 }, { 5, 13 } } },
                  { 61, false, { { 2, 5 }, { 5, 13 }, { 4, 6, 12 } } },
                  { 62, false, { { 1, 4, 17 }, { 4, 6, 12 }, { 3, 5 } } },
                  { 63, false, { { 3, 16 }, { 3, 5 }, { 2, 4, 6 } } },
                  { 64, false, { { 2, 7, 15 }, { 2, 4, 6 }, { 1, 3, 5 } } },
                  { 65, false, { { 1, 6, 14 }, { 1, 3, 5 }, { 2, 4, 16 } } },
                  { 66, false, { { 5, 7, 13 }, { 2, 4, 16 }, { 1, 3, 6, 15 } } },
                  { 67, false, { { 4, 6, 12 }, { 1, 3, 6, 15 }, { 2, 5, 14 } } },
                  { 68, false, { { 3, 5, 7 }, { 2, 5, 14 }, { 1, 4, 13, 16 } } },
                  { 69, false, { { 2, 4, 6 }, { 1, 4, 13, 16 }, { 3, 12, 15, 16 } } },
                  { 70, false, { { 1, 3, 5, 17 }, { 3, 12, 15, 16 }, { 2, 6, 14, 15 } } },
                  { 71, false, { { 2, 4, 7, 16 }, { 2, 6, 14, 15 }, { 1, 5, 6, 13, 14 } } },
                  { 72, false, { { 1, 3, 6, 15 }, { 1, 5, 6, 13, 14 }, { 4, 5, 6, 12, 13 } } },
                  { 73, false, { { 2, 5, 14, 17 }, { 4, 5, 6, 12, 13 }, { 3, 4, 5, 6, 12 } } },
                  { 74, false, { { 1, 4, 13, 16, 17 }, { 3, 4, 5, 12 }, { 2, 3, 4, 5 } } },
            },
            // alto
            {
                  { 33, true, { { 7 }, { 2 }, { 1 } } },
                  { 34, true, { { 6 }, { 1 }, {} } },
                  { 35, true, { { 5 }, {}, {} } },
                  { 36, true, { { 4 }, {}, {} } },
                  { 37, true, { { 3 }, {}, {} } },
                  { 38, true, { { 2 }, {}, {} } },
                  { 39, true, { { 1 }, {}, {} } },
                  { 45, false, { { 7 }, { 2 }, { 1 } } },
                  { 46, false, { { 6 }, { 1 }, {} } },
                  { 47, false, { { 5 }, {}, { 6 } } },
                  { 48, false, { { 4 }, { 6 }, { 5 } } },
                  { 49, false, { { 3 }, { 5 }, { 4 } } },
                  { 50, false, { { 2 }, { 4 }, { 3 } } },
                  { 51, false, { { 1 }, { 3 }, { 2 } } },
                  { 52, false, { { 7 }, { 2 }, { 1, 6 } } },
                  { 53, false, { { 6 }, { 1, 6 }, { 5 } } },
                  { 54, false, { { 5 }, { 5 }, { 4 } } },
                  { 55, false, { { 4 }, { 4 }, { 3 } } },
                  { 56, false, { { 3 }, { 3 }, { 2, 6 } } },
                  { 57, false, { { 2, 7 }, { 2, 6 }, { 1, 5 } } },
                  { 58, false, { { 1, 6 }, { 1, 5 }, { 4 } } },
                  { 59, false, { { 5 }, { 4 }, { 3, 6 } } },
                  { 60, false, { { 4 }, { 3, 6 }, { 2, 5 } } },
                  { 61, false, { { 3, 7 }, { 2, 5 }, { 1, 4 } } },
                  { 62, false, { { 2, 6 }, { 1, 4 }, { 3, 16 } } },
                  { 63, false, { { 1, 5 }, { 3, 16 }, { 2, 15 } } },
                  { 64, false, { { 4, 7 }, { 2, 15 }, { 1, 6, 14 } } },
                  { 65, false, { { 3, 6 }, { 1, 6, 14 }, { 5, 13 } } },
                  { 66, false, { { 2, 5 }, { 5, 13 }, { 4, 6, 12 } } },
                  { 67, false, { { 1, 4, 17 }, { 4, 6, 12 }, { 3, 5 } } },
                  { 68, false, { { 3, 16 }, { 3, 5 }, { 2, 4, 6 } } },
                  { 69, false, { { 2, 7, 15 }, { 2, 4, 6 }, { 1, 3, 5 } } },
                  { 70, false, { { 1, 6, 14 }, { 1, 3, 5 }, { 2, 4, 16 } } },
                  { 71, false, { { 5, 7, 13 }, { 2, 4, 16 }, { 1, 3, 6, 15 } } },
                  { 72, false, { { 4, 6, 12 }, { 1, 3, 6, 15 }, { 2, 5, 14 } } },
                  { 73, false, { { 3, 5, 7 }, { 2, 5, 14 }, { 1, 4, 13, 16 } } },
                  { 74, false, { { 2, 4, 6 }, { 1, 4, 13, 16 }, { 3, 12, 15, 16 } } },
                  { 75, false, { { 1, 3, 5, 17 }, { 3, 12, 15, 16 }, { 2, 6, 14, 15 } } },
                  { 76, false, { { 2, 4, 7, 16 }, { 2, 6, 14, 15 }, { 1, 5, 6, 13, 14 } } },
                  { 77, false, { { 1, 3, 6, 15 }, { 1, 5, 6, 13, 14 }, { 4, 5, 6, 12, 13 } } },
                  { 78, false, { { 2, 5, 14, 17 }, { 4, 5, 6, 12, 13 }, { 3, 4, 5, 6, 12 } } },
                  { 79, false, { { 1, 4, 13, 16, 17 }, { 3, 4, 5, 12 }, { 2, 3, 4, 5 } } },
            },
            // contrabass
            {
                  { 16, true, { { 7 }, { 2 }, { 1 } } },
                  { 17, true, { { 6 }, { 1 }, {} } },
                  { 18, true, { { 5 }, {}, {} } },
                  { 19, true, { { 4 }, {}, {} } },
                  { 20, true, { { 3 }, {}, {} } },
                  { 21, true, { { 2 }, {}, {} } },
                  { 22, true, { { 1 }, {}, {} } },
                  { 28, false, { { 7 }, { 2 }, { 1 } } },
                  { 29, false, { { 6 }, { 1 }, {} } },
                  { 30, false, { { 5 }, {}, { 6 } } },
                  { 31, false, { { 4 }, { 6 }, { 5 } } },
                  { 32, false, { { 3 }, { 5 }, { 4 } } },
                  { 33, false, { { 2 }, { 4 }, { 3 } } },
                  { 34, false, { { 1 }, { 3 }, { 2 } } },
                  { 35, false, { { 7 }, { 2 }, { 1, 6 } } },
                  { 36, false, { { 6 }, { 1, 6 }, { 5 } } },
                  { 37, false, { { 5 }, { 5 }, { 4 } } },
                  { 38, false, { { 4 }, { 4 }, { 3 } } },
                  { 39, false, { { 3 }, { 3 }, { 2, 6 } } },
                  { 40, false, { { 2, 7 }, { 2, 6 }, { 1, 5 } } },
                  { 41, false, { { 1, 6 }, { 1, 5 }, { 4 } } },
                  { 42, false, { { 5 }, { 4 }, { 3, 6 } } },
                  { 43, false, { { 4 }, { 3, 6 }, { 2, 5 } } },
                  { 44, false, { { 3, 7 }, { 2, 5 }, { 1, 4 } } },
                  { 45, false, { { 2, 6 }, { 1, 4 }, { 3, 16 } } },
                  { 46, false, { { 1, 5 }, { 3, 16 }, { 2, 15 } } },
                  { 47, false, { { 4, 7 }, { 2, 15 }, { 1, 6, 14 } } },
                  { 48, false, { { 3, 6 }, { 1, 6, 14 }, { 5, 13 } } },
                  { 49, false, { { 2, 5 }, { 5, 13 }, { 4, 6, 12 } } },
                  { 50, false, { { 1, 4, 17 }, { 4, 6, 12 }, { 3, 5 } } },
                  { 51, false, { { 3, 16 }, { 3, 5 }, { 2, 4, 6 } } },
                  { 52, false, { { 2, 7, 15 }, { 2, 4, 6 }, { 1, 3, 5 } } },
                  { 53, false, { { 1, 6, 14 }, { 1, 3, 5 }, { 2, 4, 16 } } },
                  { 54, false, { { 5, 7, 13 }, { 2, 4, 16 }, { 1, 3, 6, 15 } } },
                  { 55, false, { { 4, 6, 12 }, { 1, 3, 6, 15 }, { 2, 5, 14 } } },
                  { 56, false, { { 3, 5, 7 }, { 2, 5, 14 }, { 1, 4, 13, 16 } } },
                  { 57, false, { { 2, 4, 6 }, { 1, 4, 13, 16 }, { 3, 12, 15, 16 } } },
                  { 58, false, { { 1, 3, 5, 17 }, { 3, 12, 15, 16 }, { 2, 6, 14, 15 } } },
                  { 59, false, { { 2, 4, 7, 16 }, { 2, 6, 14, 15 }, { 1, 5, 6, 13, 14 } } },
                  { 60, false, { { 1, 3, 6, 15 }, { 1, 5, 6, 13, 14 }, { 4, 5, 6, 12, 13 } } },
                  { 61, false, { { 2, 5, 14, 17 }, { 4, 5, 6, 12, 13 }, { 3, 4, 5, 6, 12 } } },
                  { 62, false, { { 1, 4, 13, 16, 17 }, { 3, 4, 5, 12 }, { 2, 3, 4, 5 } } },
            },
            };
      return ROWS[int(c)];
      }

// the fundamental of position 1 on each side (position n: n - 1 semitones lower)
inline int slideFundamental(SlideChart c, int side)
      {
      static const int FUND[3][3] = {
            { 34, 29, 28 },
            { 39, 34, 33 },
            { 22, 17, 16 },
            };
      return FUND[int(c)][side];
      }

// the most positions a side's row uses
constexpr int SLIDE_SIDE_POSITIONS[3] = { 7, 6, 6 };

//---------------------------------------------------------
//   valve fingerings: one chart for five staves. Masks: bit 0 valve 1 ... bit 4 valve 5, 0 open.
//   Rows: 0 the 3-valve row, 1 the +4th-valve row, 2 the +5th-valve row. A column is the
//   semitones above the open fundamental.
//---------------------------------------------------------

enum class ValveColumn : char { TREBLE, EUPHONIUM, F_TUBA, CC_TUBA, BBB_TUBA };
// the treble column at written pitch, the others sounding

struct ValveCell {
      int mask;
      int row;
      };

struct ValveRow {
      int rel;
      bool pedal;                   // in the chart's pedal-tone bracket
      std::vector<ValveCell> fingerings;
      };

inline const std::vector<ValveRow>& valveRows()
      {
      static const std::vector<ValveRow> ROWS = {
            { -6, true, { { 0x07, 0 }, { 0x0a, 1 }, { 0x11, 2 } } },
            { -5, true, { { 0x05, 0 }, { 0x08, 1 }, { 0x12, 2 } } },
            { -4, true, { { 0x06, 0 }, { 0x10, 2 } } },
            { -3, true, { { 0x03, 0 }, { 0x04, 0 }, { 0x1f, 2 } } },
            { -2, true, { { 0x01, 0 }, { 0x1d, 2 } } },
            { -1, true, { { 0x02, 0 }, { 0x1e, 2 } } },
            { 0, true, { { 0x00, 0 }, { 0x1b, 2 }, { 0x1c, 2 } } },
            { 1, false, { { 0x0f, 1 }, { 0x1d, 2 }, { 0x19, 2 } } },
            { 2, false, { { 0x0d, 1 }, { 0x1c, 2 }, { 0x1b, 2 } } },
            { 3, false, { { 0x0e, 1 }, { 0x1a, 2 } } },
            { 4, false, { { 0x0b, 1 }, { 0x15, 2 }, { 0x18, 2 } } },
            { 5, false, { { 0x09, 1 }, { 0x16, 2 } } },
            { 6, false, { { 0x07, 0 }, { 0x0a, 1 }, { 0x13, 2 } } },
            { 7, false, { { 0x05, 0 }, { 0x08, 1 }, { 0x12, 2 }, { 0x1c, 2 }, { 0x1b, 2 } } },
            { 8, false, { { 0x06, 0 }, { 0x0f, 1 }, { 0x10, 2 }, { 0x1c, 2 } } },
            { 9, false, { { 0x03, 0 }, { 0x04, 0 }, { 0x0d, 1 }, { 0x17, 2 }, { 0x1a, 2 }, { 0x1f, 2 } } },
            { 10, false, { { 0x01, 0 }, { 0x0e, 1 }, { 0x15, 2 }, { 0x1d, 2 }, { 0x18, 2 } } },
            { 11, false, { { 0x02, 0 }, { 0x0c, 1 }, { 0x0b, 1 }, { 0x16, 2 }, { 0x1e, 2 } } },
            { 12, false, { { 0x00, 0 }, { 0x09, 1 }, { 0x13, 2 }, { 0x1c, 2 }, { 0x1b, 2 }, { 0x14, 2 } } },
            { 13, false, { { 0x07, 0 }, { 0x0a, 1 }, { 0x0f, 1 }, { 0x11, 2 }, { 0x1f, 2 }, { 0x19, 2 } } },
            { 14, false, { { 0x05, 0 }, { 0x08, 1 }, { 0x0d, 1 }, { 0x12, 2 }, { 0x1a, 2 }, { 0x17, 2 } } },
            { 15, false, { { 0x06, 0 }, { 0x0e, 1 }, { 0x15, 2 }, { 0x1e, 2 }, { 0x18, 2 }, { 0x10, 2 } } },
            { 16, false, { { 0x03, 0 }, { 0x0c, 1 }, { 0x0b, 1 }, { 0x16, 2 }, { 0x1f, 2 }, { 0x1c, 2 }, { 0x1b, 2 } } },
            { 17, false, { { 0x01, 0 }, { 0x09, 1 }, { 0x0f, 1 }, { 0x14, 2 }, { 0x1d, 2 }, { 0x19, 2 }, { 0x13, 2 } } },
            { 18, false, { { 0x02, 0 }, { 0x07, 0 }, { 0x0a, 1 }, { 0x0d, 1 }, { 0x11, 2 }, { 0x1e, 2 }, { 0x1a, 2 }, { 0x17, 2 } } },
            { 19, false, { { 0x00, 0 }, { 0x05, 0 }, { 0x08, 1 }, { 0x0e, 1 }, { 0x12, 2 }, { 0x1c, 2 }, { 0x18, 2 }, { 0x15, 2 } } },
            };
      return ROWS;
      }

inline int valveFundamental(ValveColumn c)
      {
      static const int FUND[5] = {
            48,   // TREBLE
            34,   // EUPHONIUM
            29,   // F_TUBA
            24,   // CC_TUBA
            22,   // BBB_TUBA
            };
      return FUND[int(c)];
      }

//---------------------------------------------------------
//   double horn in F, WRITTEN pitch: F side and B-flat side (masks with HORN_THUMB)
//---------------------------------------------------------

constexpr int HORN_THUMB = 0x20;

struct HornRow {
      int written;
      std::vector<int> f;
      std::vector<int> bb;
      };

inline const std::vector<HornRow>& hornRows()
      {
      static const std::vector<HornRow> ROWS = {
            { 36, { 0x00 }, { 0x25 } },
            { 37, {  }, { 0x26 } },
            { 38, {  }, { 0x23, 0x24 } },
            { 39, {  }, { 0x21 } },
            { 40, {  }, { 0x22 } },
            { 41, {  }, { 0x20 } },
            { 42, { 0x07 }, {  } },
            { 43, { 0x05 }, {  } },
            { 44, { 0x06 }, {  } },
            { 45, { 0x03, 0x04 }, {  } },
            { 46, { 0x01 }, {  } },
            { 47, { 0x02 }, { 0x27 } },
            { 48, { 0x00 }, { 0x25 } },
            { 49, { 0x07 }, { 0x26 } },
            { 50, { 0x05 }, { 0x23, 0x24 } },
            { 51, { 0x06 }, { 0x21 } },
            { 52, { 0x03, 0x04 }, { 0x22 } },
            { 53, { 0x01 }, { 0x20 } },
            { 54, { 0x02, 0x07 }, { 0x27 } },
            { 55, { 0x00, 0x05 }, { 0x25 } },
            { 56, { 0x06 }, { 0x26 } },
            { 57, { 0x03, 0x04 }, { 0x23, 0x24 } },
            { 58, { 0x01, 0x07 }, { 0x21 } },
            { 59, { 0x02, 0x05 }, { 0x22, 0x27 } },
            { 60, { 0x00, 0x06 }, { 0x20, 0x25 } },
            { 61, { 0x03, 0x04, 0x07 }, { 0x26 } },
            { 62, { 0x01, 0x05 }, { 0x23, 0x24 } },
            { 63, { 0x02, 0x06 }, { 0x21, 0x27 } },
            { 64, { 0x00, 0x03, 0x04 }, { 0x22, 0x25 } },
            { 65, { 0x01 }, { 0x20, 0x26 } },
            { 66, { 0x02, 0x07 }, { 0x23, 0x24, 0x27 } },
            { 67, { 0x00, 0x05 }, { 0x21, 0x25 } },
            { 68, { 0x06, 0x07 }, { 0x22, 0x26 } },
            { 69, { 0x03, 0x04, 0x05 }, { 0x23, 0x24, 0x20 } },
            { 70, { 0x01, 0x06, 0x07 }, { 0x21 } },
            { 71, { 0x02, 0x03, 0x04, 0x05 }, { 0x22, 0x27 } },
            { 72, { 0x00, 0x01, 0x06 }, { 0x20, 0x25 } },
            { 73, { 0x02, 0x03, 0x04, 0x07 }, { 0x26, 0x27 } },
            { 74, { 0x00, 0x01, 0x05 }, { 0x23, 0x24, 0x25 } },
            { 75, { 0x02, 0x06 }, { 0x21, 0x26, 0x27 } },
            { 76, { 0x00, 0x03, 0x04 }, { 0x22, 0x23, 0x24, 0x25 } },
            { 77, { 0x01, 0x07 }, { 0x20, 0x21, 0x26 } },
            { 78, { 0x02, 0x05, 0x07 }, { 0x22, 0x23, 0x24, 0x27 } },
            { 79, { 0x00, 0x05, 0x06 }, { 0x20, 0x21, 0x25 } },
            { 80, { 0x06, 0x07, 0x03, 0x04 }, { 0x26, 0x22 } },
            { 81, { 0x03, 0x04, 0x01, 0x05 }, { 0x23, 0x24, 0x20, 0x27 } },
            { 82, { 0x01, 0x02, 0x06, 0x07 }, { 0x21, 0x25 } },
            { 83, { 0x02, 0x03, 0x04, 0x05, 0x00 }, { 0x22, 0x26, 0x27 } },
            { 84, { 0x00, 0x01, 0x06, 0x07 }, { 0x20, 0x23, 0x24, 0x25 } },
            { 85, { 0x00, 0x02, 0x03, 0x04, 0x05, 0x07 }, { 0x21, 0x26, 0x27 } },
            { 86, { 0x00, 0x02, 0x01, 0x06, 0x05 }, { 0x22, 0x23, 0x24, 0x25 } },
            { 87, { 0x00, 0x02, 0x03, 0x04, 0x06 }, { 0x20, 0x21, 0x26, 0x27 } },
            { 88, { 0x00, 0x01, 0x03, 0x04 }, { 0x22, 0x23, 0x24, 0x25 } },
            { 89, { 0x02, 0x01, 0x07 }, { 0x20, 0x21, 0x26 } },
            };
      return ROWS;
      }

constexpr int HORN_FUNDAMENTAL_F = 36;      // written
constexpr int HORN_FUNDAMENTAL_BB = 41;

}     // namespace Playability
}     // namespace Ms
#endif
