//=============================================================================
//  MuseScore
//  Music Composition & Notation
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License version 2
//  as published by the Free Software Foundation and appearing in
//  the file LICENCE.GPL
//=============================================================================

// Generated by tools/playability/gen_winds.py from the owner's sourcebook (T1 ranges,
// T2 registers, T19 dynamic curves; kept outside this repository). Do not edit by hand.
// Per instrument (MuseScore's instrument id): transposition written -> sounding, the graph's range (T1,
// else MuseScore's), register stripes with their words (T2; WIND_BOTTOM / WIND_TOP = the axis
// ends), the dynamic curve [pitch, width] (T19, 1 = widest) and a pedal part. SOUNDING pitches.

#ifndef __PLAYABILITYWINDS_H__
#define __PLAYABILITYWINDS_H__

#include <map>
#include <vector>
#include <QString>

namespace Ms {
namespace Playability {

constexpr int WIND_BOTTOM = -1000;
constexpr int WIND_TOP = 1000;

struct WindBand {
      int lo;
      int hi;
      const char* words;
      };

struct WindData {
      int tr;
      bool hasRange;
      int rangeLo;
      int rangeHi;
      std::vector<WindBand> bands;
      std::vector<std::pair<double, double>> curve;
      std::vector<std::pair<double, double>> pedal;
      const char* family;
      };

struct WindId {
      bool anyKey;                                        // any key in the name (horn, tuba)
      std::vector<std::pair<const char*, const char*>> variants;    // key in the part's name -> id
      };

inline const std::map<QString, WindData>& windData()
      {
      static const std::map<QString, WindData> DATA = {
            { "piccolo", { 12, true, 74, 108, { { 74, 80, "Quiet, hauntingly hollow sound" }, { 81, 92, "Soft and mellow" }, { 93, 102, "Bright and clear" }, { 103, 108, "Shrill" } }, { { 72, 0.17 }, { 86, 0.32 }, { 101, 0.51 }, { 110, 1.0 } }, {}, "Flutes" } },
            { "flute", { 0, true, 59, 98, { { 59, 68, "Weak, but luscious" }, { 69, 80, "Sweet, but with little carrying power" }, { 81, 92, "Clear and brilliant" }, { 93, 98, "A bit shrill" } }, { { 60, 0.17 }, { 74, 0.32 }, { 89, 0.51 }, { 98, 1.0 } }, {}, "Flutes" } },
            { "alto-flute", { -5, true, 55, 91, { { 55, 66, "Deep, rich and sonorous" }, { 67, 80, "Full and quite effective" }, { 81, 91, "Ordinary and without the brilliance of the flute" } }, { { 55, 0.17 }, { 69, 0.32 }, { 84, 0.51 }, { 93, 1.0 } }, {}, "Flutes" } },
            { "bass-flute", { -12, false, 0, 0, { { 48, 61, "Warm, dark, little ability to penetrate" }, { 62, 76, "Brighter, carries well" }, { 77, 86, "Brilliant, penetrating, shrill when needed" } }, { { 48, 0.17 }, { 62, 0.32 }, { 77, 0.51 }, { 86, 1.0 } }, {}, "Flutes" } },
            { "oboe", { 0, true, 58, 93, { { 58, 66, "Thick, heavy" }, { 67, 82, "Warm, prominent, reedy, and poignant" }, { 83, 88, "Thin but clear" }, { 89, 93, "Pinched and ineffective" } }, { { 58, 1.0 }, { 93, 0.23 } }, {}, "Oboes" } },
            { "english-horn", { -7, true, 52, 84, { { 52, 61, "Deep, rich, intense" }, { 62, 75, "Mellow, reedy, sonorous" }, { 76, 84, "Thin, pinched" } }, { { 51, 1.0 }, { 86, 0.23 } }, {}, "Oboes" } },
            { "oboe-d'amore", { -3, false, 0, 0, { { WIND_BOTTOM, 59, "Rich, reedy (easier to control softly than the oboe)" }, { 60, 82, "Clear, penetrates most textures" }, { 83, 90, "Thinner, less rich in harmonics, still penetrates" } }, { { 55, 1.0 }, { 90, 0.23 } }, {}, "Oboes" } },
            { "heckelphone", { -12, false, 0, 0, { { WIND_BOTTOM, 50, "Dark, foreboding, haunting" }, { 51, 75, "Full, reedy, rich" }, { 76, 79, "Hoarse and nasal; the four top semitones only in forte" } }, { { 46, 1.0 }, { 81, 0.23 } }, {}, "Oboes" } },
            { "clarinet", { -2, true, 50, 91, { { 50, 64, "Chalumeau register, deep and rich" }, { 65, 68, "“Throat tones,” rather pale" }, { 69, 83, "Clarino register, bright, incisive, expressive" }, { 84, 91, "Piercing, shrill" } }, { { 50, 0.76 }, { 64, 0.32 }, { 68, 0.32 }, { 69, 0.32 }, { 91, 1.0 } }, {}, "Clarinets" } },
            { "bb-clarinet", { -2, true, 50, 91, { { 50, 64, "Chalumeau register, deep and rich" }, { 65, 68, "“Throat tones,” rather pale" }, { 69, 83, "Clarino register, bright, incisive, expressive" }, { 84, 91, "Piercing, shrill" } }, { { 50, 0.76 }, { 64, 0.32 }, { 68, 0.32 }, { 69, 0.32 }, { 91, 1.0 } }, {}, "Clarinets" } },
            { "a-clarinet", { -3, true, 49, 90, { { 49, 63, "Chalumeau register, deep and rich" }, { 64, 67, "“Throat tones,” rather pale" }, { 68, 82, "Clarino register, bright, incisive, expressive" }, { 83, 90, "Piercing, shrill" } }, { { 49, 0.76 }, { 63, 0.32 }, { 67, 0.32 }, { 68, 0.32 }, { 90, 1.0 } }, {}, "Clarinets" } },
            { "c-clarinet", { 0, false, 0, 0, { { WIND_BOTTOM, 66, "Chalumeau, very dark and rich" }, { 67, 70, "Throat tones, pale, almost “fuzzy”" }, { 71, 84, "Clarino, bright and lively" }, { 85, WIND_TOP, "Increasingly flutelike; may be shrill at f" } }, { { 52, 0.76 }, { 66, 0.32 }, { 70, 0.32 }, { 71, 0.32 }, { 93, 1.0 } }, {}, "Clarinets" } },
            { "d-clarinet", { 2, false, 0, 0, { { WIND_BOTTOM, 68, "Chalumeau, very dark and rich" }, { 69, 72, "Throat tones, pale, almost “fuzzy”" }, { 73, 86, "Clarino, bright and lively" }, { 87, WIND_TOP, "Increasingly flutelike; may be shrill at f" } }, { { 54, 0.76 }, { 68, 0.32 }, { 72, 0.32 }, { 73, 0.32 }, { 95, 1.0 } }, {}, "Clarinets" } },
            { "eb-clarinet", { 3, true, 55, 96, { { 55, 69, "Chalumeau register, deep and rich" }, { 70, 73, "“Throat tones,” rather pale" }, { 74, 88, "Clarino register, bright, incisive, expressive" }, { 89, 96, "Piercing, shrill" } }, { { 55, 0.76 }, { 69, 0.32 }, { 73, 0.32 }, { 74, 0.32 }, { 96, 1.0 } }, {}, "Clarinets" } },
            { "alto-clarinet", { -9, false, 0, 0, { { WIND_BOTTOM, 57, "Chalumeau, very dark and rich" }, { 58, 61, "Throat tones, pale, almost “fuzzy”" }, { 62, 75, "Clarino, bright and lively" }, { 76, WIND_TOP, "Increasingly flutelike; may be shrill at f" } }, { { 43, 0.76 }, { 57, 0.32 }, { 61, 0.32 }, { 62, 0.32 }, { 84, 1.0 } }, {}, "Clarinets" } },
            { "basset-horn", { -7, false, 0, 0, { { WIND_BOTTOM, 59, "Chalumeau, very dark and rich" }, { 60, 63, "Throat tones, pale, almost “fuzzy”" }, { 64, 77, "Clarino, bright and lively" }, { 78, WIND_TOP, "Increasingly flutelike; may be shrill at f" } }, { { 45, 0.76 }, { 59, 0.32 }, { 63, 0.32 }, { 64, 0.32 }, { 86, 1.0 } }, {}, "Clarinets" } },
            { "bass-clarinet", { -14, true, 36, 74, { { 36, 54, "Chalumeau register (written D3 and E♭3 are not on every instrument)" }, { 55, 66, "Clarino register" }, { 67, 74, "Thin sounding" } }, { { 38, 0.76 }, { 52, 0.32 }, { 56, 0.32 }, { 57, 0.32 }, { 79, 1.0 } }, {}, "Clarinets" } },
            { "bb-bass-clarinet", { -14, true, 36, 74, { { 36, 54, "Chalumeau register (written D3 and E♭3 are not on every instrument)" }, { 55, 66, "Clarino register" }, { 67, 74, "Thin sounding" } }, { { 38, 0.76 }, { 52, 0.32 }, { 56, 0.32 }, { 57, 0.32 }, { 79, 1.0 } }, {}, "Clarinets" } },
            { "contra-alto-clarinet", { -21, false, 0, 0, { { WIND_BOTTOM, 45, "Chalumeau, very dark and rich" }, { 46, 49, "Throat tones, pale, almost “fuzzy”" }, { 50, 63, "Clarino, bright and lively" }, { 64, WIND_TOP, "Increasingly flutelike; may be shrill at f" } }, { { 31, 0.76 }, { 45, 0.32 }, { 49, 0.32 }, { 50, 0.32 }, { 72, 1.0 } }, {}, "Clarinets" } },
            { "contrabass-clarinet", { -26, false, 0, 0, { { WIND_BOTTOM, 40, "Chalumeau, very dark and rich" }, { 41, 44, "Throat tones, pale, almost “fuzzy”" }, { 45, 58, "Clarino, bright and lively" }, { 59, WIND_TOP, "Increasingly flutelike; may be shrill at f" } }, { { 26, 0.76 }, { 40, 0.32 }, { 44, 0.32 }, { 45, 0.32 }, { 67, 1.0 } }, {}, "Clarinets" } },
            { "bassoon", { 0, true, 34, 75, { { 34, 44, "Sonorous, dark, vibrant" }, { 45, 63, "Sweet, more subdued, but expressive" }, { 64, 70, "Thin but intense" }, { 71, 75, "Thin and often pinched" } }, { { 34, 1.0 }, { 76, 0.2 } }, {}, "Bassoons" } },
            { "contrabassoon", { -12, true, 22, 58, { { 22, 31, "Brittle and dry; soft attacks and true pianissimo almost impossible" }, { 32, 49, "More “horn-like” and transparent; blends well" }, { 50, WIND_TOP, "Very focused, bright nasal quality; does not penetrate well" } }, { { 22, 1.0 }, { 64, 0.2 } }, {}, "Bassoons" } },
            { "sopranino-saxophone", { 3, true, 61, 94, { { WIND_BOTTOM, 69, "Very rich, reedy and full; velvety legato" }, { 70, 87, "Progressively more delicate, smooth, “flutey”" }, { 88, WIND_TOP, "Like a very rich string-flute tone" } }, { { 61, 1.0 }, { 73, 0.64 }, { 99, 0.35 } }, {}, "Saxophones" } },
            { "soprano-saxophone", { -2, true, 56, 89, { { 56, 63, "Hard to play very softly (lowest 5th)" }, { 64, 86, "“Can be controlled beautifully” (after the first P5, almost two octaves)" } }, { { 56, 1.0 }, { 68, 0.64 }, { 94, 0.35 } }, {}, "Saxophones" } },
            { "alto-saxophone", { -9, true, 49, 82, { { 49, 56, "Hard to play very softly (lowest 5th)" }, { 57, 79, "“Can be controlled beautifully” (after the first P5, almost two octaves)" } }, { { 49, 1.0 }, { 61, 0.64 }, { 87, 0.35 } }, {}, "Saxophones" } },
            { "tenor-saxophone", { -14, true, 44, 77, { { 44, 51, "Hard to play very softly (lowest 5th)" }, { 52, 74, "“Can be controlled beautifully” (after the first P5, almost two octaves)" } }, { { 44, 1.0 }, { 56, 0.64 }, { 82, 0.35 } }, {}, "Saxophones" } },
            { "saxophone", { -14, true, 44, 77, { { 44, 51, "Hard to play very softly (lowest 5th)" }, { 52, 74, "“Can be controlled beautifully” (after the first P5, almost two octaves)" } }, { { 44, 1.0 }, { 56, 0.64 }, { 82, 0.35 } }, {}, "Saxophones" } },
            { "baritone-saxophone", { -21, true, 37, 70, { { WIND_BOTTOM, 45, "Very rich, reedy and full; velvety legato" }, { 46, 63, "Progressively more delicate, smooth, “flutey”" }, { 64, WIND_TOP, "Like a very rich string-flute tone" } }, { { 37, 1.0 }, { 49, 0.64 }, { 75, 0.35 } }, {}, "Saxophones" } },
            { "bass-saxophone", { -26, true, 32, 65, { { WIND_BOTTOM, 40, "Very rich, reedy and full; velvety legato" }, { 41, 58, "Progressively more delicate, smooth, “flutey”" }, { 59, WIND_TOP, "Like a very rich string-flute tone" } }, { { 32, 1.0 }, { 44, 0.64 }, { 70, 0.35 } }, {}, "Saxophones" } },
            { "horn", { -7, true, 31, 77, { { 41, 47, "Dark and a bit unfocused" }, { 48, 52, "Deep and solid" }, { 53, 71, "Bright and heroic" }, { 72, 77, "Brilliant and loud" } }, { { 31, 0.44 }, { 36, 0.64 }, { 46, 0.3 }, { 77, 1.0 } }, {}, "Horn" } },
            { "trumpet", { -2, true, 52, 82, { { 52, 57, "Rather dull" }, { 58, 80, "Clear, bright, and most articulate" }, { 81, 84, "Brilliant but strident" } }, { { 52, 0.71 }, { 84, 1.0 } }, {}, "Trumpets" } },
            { "bb-trumpet", { -2, true, 52, 82, { { 52, 57, "Rather dull" }, { 58, 80, "Clear, bright, and most articulate" }, { 81, 84, "Brilliant but strident" } }, { { 52, 0.71 }, { 84, 1.0 } }, {}, "Trumpets" } },
            { "c-trumpet", { 0, true, 54, 84, { { 54, 59, "Rather dull" }, { 60, 82, "Clear, bright, and most articulate" }, { 83, 86, "Brilliant but strident" } }, { { 54, 0.71 }, { 86, 1.0 } }, {}, "Trumpets" } },
            { "bb-cornet", { -2, true, 52, 82, { { 52, 57, "Rather dull" }, { 58, 80, "Clear, bright, articulate — a little mellower than the trumpet" }, { 81, 84, "Brilliant but strident" } }, { { 52, 0.71 }, { 84, 1.0 } }, {}, "Trumpets" } },
            { "flugelhorn", { -2, true, 52, 82, { { 52, 78, "Very mellow, lush; close to the horn" }, { 79, 84, "Top fourth — not generally used" } }, { { 52, 0.71 }, { 84, 1.0 } }, {}, "Trumpets" } },
            { "c-bass-trumpet", { -12, false, 0, 0, { { 42, 47, "Extreme: hardest to attack, least satisfactory" }, { 48, 72, "Most useful register" }, { 73, 76, "Extreme: hardest to attack, least satisfactory" } }, { { 42, 0.71 }, { 74, 1.0 } }, {}, "Trumpets" } },
            { "bb-bass-trumpet", { -14, false, 0, 0, { { 40, 45, "Extreme: hardest to attack, least satisfactory" }, { 46, 70, "Most useful register; dark, full, sonorous" }, { 71, 74, "Extreme: hardest to attack, least satisfactory" } }, { { 40, 0.71 }, { 72, 1.0 } }, {}, "Trumpets" } },
            { "eb-bass-trumpet", { -9, true, 44, 75, {  }, { { 45, 0.71 }, { 77, 1.0 } }, {}, "Trumpets" } },
            { "trombone", { 0, true, 40, 77, { { 40, 44, "Dark, less strong" }, { 45, 66, "Firm and powerful" }, { 67, 70, "Very intense" } }, { { 40, 0.55 }, { 74, 1.0 } }, { { 28, 0.46 }, { 34, 0.65 } }, "Tenor trombone" } },
            { "tenor-trombone", { 0, true, 40, 77, { { 40, 44, "Dark, less strong" }, { 45, 66, "Firm and powerful" }, { 67, 70, "Very intense" } }, { { 40, 0.55 }, { 74, 1.0 } }, { { 28, 0.46 }, { 34, 0.65 } }, "Tenor trombone" } },
            { "bass-trombone", { 0, true, 34, 70, { { 34, 42, "Heavy and quite strong" }, { 43, 56, "Deep and solid" }, { 57, 70, "Very powerful" } }, {}, {}, "" } },
            { "alto-trombone", { 0, true, 45, 75, { { 45, 50, "Poor in quality, rarely used" }, { 51, 75, "The usable two octaves" }, { 76, 79, "“For all orchestral purposes unplayable”" } }, {}, {}, "" } },
            { "tuba", { 0, true, 26, 67, { { 26, 35, "Deep and heavy" }, { 36, 52, "Very strong" }, { 53, 67, "Getting weaker but quite intense" } }, { { 29, 0.66 }, { 62, 1.0 } }, {}, "Tubas" } },
            { "bb-tuba", { 0, true, 26, 67, { { 26, 35, "Deep and heavy" }, { 36, 52, "Very strong" }, { 53, 67, "Getting weaker but quite intense" } }, { { 29, 0.66 }, { 62, 1.0 } }, {}, "Tubas" } },
            { "c-tuba", { 0, true, 26, 67, { { 26, 35, "Deep and heavy" }, { 36, 52, "Very strong" }, { 53, 67, "Getting weaker but quite intense" } }, { { 29, 0.66 }, { 62, 1.0 } }, {}, "Tubas" } },
            { "f-tuba", { 0, true, 26, 67, { { 26, 35, "Deep and heavy" }, { 36, 52, "Very strong" }, { 53, 67, "Getting weaker but quite intense" } }, { { 29, 0.66 }, { 62, 1.0 } }, {}, "Tubas" } },
            { "eb-tuba", { 0, true, 26, 67, { { 26, 35, "Deep and heavy" }, { 36, 52, "Very strong" }, { 53, 67, "Getting weaker but quite intense" } }, { { 29, 0.66 }, { 62, 1.0 } }, {}, "Tubas" } },
            { "euphonium", { 0, true, 34, 70, { { WIND_BOTTOM, 64, "Smooth and mellow" }, { 65, 70, "Top fourth: “a little difficult to get, and not much needed”" } }, { { 41, 0.66 }, { 74, 1.0 } }, {}, "Tubas" } },
            { "wagner-tuba", { -7, false, 0, 0, {  }, { { 47, 0.55 }, { 77, 1.0 } }, {}, "Wagner tuba group" } },
            { "f-wagner-tuba", { -7, false, 0, 0, {  }, { { 47, 0.55 }, { 77, 1.0 } }, {}, "Wagner tuba group" } },
            { "bb-wagner-tuba", { -2, false, 0, 0, {  }, { { 52, 0.55 }, { 82, 1.0 } }, {}, "Wagner tuba group" } },
            { "eb-alto-horn", { -9, false, 0, 0, {  }, { { 45, 0.55 }, { 75, 1.0 } }, {}, "Wagner tuba group" } },
            { "f-alto-horn", { -7, false, 0, 0, {  }, { { 47, 0.55 }, { 77, 1.0 } }, {}, "Wagner tuba group" } },
            { "mellophone", { -7, false, 0, 0, {  }, { { 47, 0.55 }, { 77, 1.0 } }, {}, "Wagner tuba group" } },
            };
      return DATA;
      }

// MusicXML instrument id -> MuseScore instrument ids
inline const std::map<QString, WindId>& windIds()
      {
      static const std::map<QString, WindId> IDS = {
            { "wind.flutes.flute.piccolo", { false, { { "C", "piccolo" } } } },
            { "wind.flutes.flute", { false, { { "C", "flute" } } } },
            { "wind.flutes.flute.alto", { false, { { "G", "alto-flute" } } } },
            { "wind.flutes.flute.bass", { false, { { "C", "bass-flute" } } } },
            { "wind.reed.oboe", { false, { { "C", "oboe" } } } },
            { "wind.reed.english-horn", { false, { { "F", "english-horn" } } } },
            { "wind.reed.oboe-damore", { false, { { "A", "oboe-d'amore" } } } },
            { "wind.reed.heckelphone", { false, { { "C", "heckelphone" } } } },
            { "wind.reed.clarinet", { false, { { "Bb", "clarinet" }, { "C", "c-clarinet" }, { "D", "d-clarinet" } } } },
            { "wind.reed.clarinet.bflat", { false, { { "Bb", "bb-clarinet" } } } },
            { "wind.reed.clarinet.a", { false, { { "A", "a-clarinet" } } } },
            { "wind.reed.clarinet.eflat", { false, { { "Eb", "eb-clarinet" } } } },
            { "wind.reed.clarinet.alto", { false, { { "Eb", "alto-clarinet" } } } },
            { "wind.reed.basset-horn", { false, { { "F", "basset-horn" } } } },
            { "wind.reed.clarinet.bass", { false, { { "Bb", "bass-clarinet" }, { "Bb", "bb-bass-clarinet" } } } },
            { "wind.reed.clarinet.contra-alto", { false, { { "Eb", "contra-alto-clarinet" } } } },
            { "wind.reed.clarinet.contrabass", { false, { { "Bb", "contrabass-clarinet" } } } },
            { "wind.reed.bassoon", { false, { { "C", "bassoon" } } } },
            { "wind.reed.contrabassoon", { false, { { "C", "contrabassoon" } } } },
            { "wind.reed.saxophone.sopranino", { false, { { "Eb", "sopranino-saxophone" } } } },
            { "wind.reed.saxophone.soprano", { false, { { "Bb", "soprano-saxophone" } } } },
            { "wind.reed.saxophone.alto", { false, { { "Eb", "alto-saxophone" } } } },
            { "wind.reed.saxophone.tenor", { false, { { "Bb", "tenor-saxophone" } } } },
            { "wind.reed.saxophone", { false, { { "Bb", "saxophone" } } } },
            { "wind.reed.saxophone.baritone", { false, { { "Eb", "baritone-saxophone" } } } },
            { "wind.reed.saxophone.bass", { false, { { "Bb", "bass-saxophone" } } } },
            { "brass.french-horn", { true, { { "F", "horn" } } } },
            { "brass.trumpet", { false, { { "Bb", "trumpet" } } } },
            { "brass.trumpet.bflat", { false, { { "Bb", "bb-trumpet" } } } },
            { "brass.trumpet.c", { false, { { "C", "c-trumpet" } } } },
            { "brass.cornet", { false, { { "Bb", "bb-cornet" } } } },
            { "brass.flugelhorn", { false, { { "Bb", "flugelhorn" } } } },
            { "brass.trumpet.bass", { false, { { "C", "c-bass-trumpet" }, { "Bb", "bb-bass-trumpet" }, { "Eb", "eb-bass-trumpet" } } } },
            { "brass.trombone", { false, { { "C", "trombone" } } } },
            { "brass.trombone.tenor", { false, { { "C", "tenor-trombone" } } } },
            { "brass.trombone.bass", { false, { { "C", "bass-trombone" } } } },
            { "brass.trombone.alto", { false, { { "C", "alto-trombone" } } } },
            { "brass.tuba", { true, { { "C", "tuba" }, { "C", "bb-tuba" }, { "C", "c-tuba" }, { "C", "f-tuba" }, { "C", "eb-tuba" } } } },
            { "brass.euphonium", { true, { { "C", "euphonium" } } } },
            { "brass.wagner-tuba", { false, { { "F", "wagner-tuba" }, { "F", "f-wagner-tuba" }, { "Bb", "bb-wagner-tuba" } } } },
            { "brass.alto-horn", { false, { { "Eb", "eb-alto-horn" }, { "F", "f-alto-horn" } } } },
            { "brass.mellophone", { false, { { "F", "mellophone" } } } },
            };
      return IDS;
      }

}     // namespace Playability
}     // namespace Ms
#endif
