#!/usr/bin/env python3
"""Generate libmscore/playabilitywinds.h (the playability checker's wind register graph data, W1)
from the Playability Checker plugin's winds.js, which that project's data/export_winds.py makes
from its sourcebook (data/tables.py: T1 ranges, T2 registers, T19 dynamic curves; every row cites
its textbook). All pitches SOUNDING MIDI.

Run:  python3 tools/playability/gen_winds.py [path/to/winds.js]
      (default ~/MuseScore/orchestration-checker/plugin/winds/winds.js)
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser('~/MuseScore/orchestration-checker/plugin/winds/winds.js')
OUT = os.path.join(HERE, '..', '..', 'libmscore', 'playabilitywinds.h')

js = open(SRC, encoding='utf-8').read()
data = json.loads(re.search(r'var WIND_DATA = (\{.*?\n\});', js, re.S).group(1))
ids = json.loads(re.search(r'var WIND_IDS = (\{.*\});', js).group(1))


def cstr(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def num(x):
    return repr(float(x)) if isinstance(x, float) else str(x)


def pitch(p, bottom):
    if p == '(bottom)':
        return 'WIND_BOTTOM'
    if p == '(top)':
        return 'WIND_TOP'
    return str(p)


def curve(c):
    return '{ ' + ', '.join('{ %s, %s }' % (num(p), num(w)) for p, w in c) + ' }' if c else '{}'


lines = []
for key in data:
    d = data[key]
    rng = d.get('range')
    bands = ', '.join('{ %s, %s, %s }' % (pitch(a, True), pitch(b, False), cstr(w)) for a, b, w in d.get('bands', []))
    lines.append('            { %s, { %s, %s, %d, %d, { %s }, %s, %s, %s } },' % (
        cstr(key), d.get('tr', 0), 'true' if rng else 'false', rng[0] if rng else 0, rng[1] if rng else 0,
        bands, curve(d.get('curve')), curve(d.get('pedal')), cstr(d.get('family') or '')))

idlines = []
for mx, e in ids.items():
    variants = ', '.join('{ %s, %s }' % (cstr(k), cstr(v)) for k, v in e['variants'])
    idlines.append('            { %s, { %s, { %s } } },' % (cstr(mx), 'true' if e['anyKey'] else 'false', variants))

out = '''//=============================================================================
//  MuseScore
//  Music Composition & Notation
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License version 2
//  as published by the Free Software Foundation and appearing in
//  the file LICENCE.GPL
//=============================================================================

// Generated by tools/playability/gen_winds.py from the Playability Checker plugin's winds.js
// (its sourcebook: T1 ranges, T2 registers, T19 dynamic curves). Do not edit by hand.
// Per instrument (the plugin's id): transposition written -> sounding, the graph's range (T1,
// else MuseScore's), register stripes with their words (T2; WIND_BOTTOM / WIND_TOP = the axis
// ends), the dynamic curve [pitch, width] (T19, 1 = widest) and a pedal part. SOUNDING pitches.

#ifndef __PLAYABILITYWINDS_H__
#define __PLAYABILITYWINDS_H__

#include <map>
#include <vector>
#include <QString>

namespace Ms {
namespace Playability {

constexpr int WIND_BOTTOM = -1000;
constexpr int WIND_TOP = 1000;

struct WindBand {
      int lo;
      int hi;
      const char* words;
      };

struct WindData {
      int tr;
      bool hasRange;
      int rangeLo;
      int rangeHi;
      std::vector<WindBand> bands;
      std::vector<std::pair<double, double>> curve;
      std::vector<std::pair<double, double>> pedal;
      const char* family;
      };

struct WindId {
      bool anyKey;                                        // any key in the name (horn, tuba)
      std::vector<std::pair<const char*, const char*>> variants;    // key in the part's name -> id
      };

inline const std::map<QString, WindData>& windData()
      {
      static const std::map<QString, WindData> DATA = {
%s
            };
      return DATA;
      }

// MusicXML instrument id -> the plugin's ids
inline const std::map<QString, WindId>& windIds()
      {
      static const std::map<QString, WindId> IDS = {
%s
            };
      return IDS;
      }

}     // namespace Playability
}     // namespace Ms
#endif
''' % ('\n'.join(lines), '\n'.join(idlines))
open(OUT, 'w', encoding='utf-8').write(out)
print('wrote %s: %d instruments, %d ids' % (os.path.relpath(OUT), len(data), len(ids)))
