#!/usr/bin/env python3
"""Generate libmscore/playabilitywindsdyn.h (the playability checker's W2/B1 register x dynamic rules)
from w2b1_rules.py (the owner's approved spec, SPEC-w2b1.md). Book and page only, no book text.

Checks before writing: every instrument id is a playabilitywinds.h key, and every band the spec
gives in two spellings (sounding and written) agrees with that instrument's transposition there.

Run:  python3 tools/playability/gen_winds_dyn.py
"""
import importlib.util, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
WINDS_H = os.path.join(HERE, '..', '..', 'libmscore', 'playabilitywinds.h')
OUT = os.path.join(HERE, '..', '..', 'libmscore', 'playabilitywindsdyn.h')

spec = importlib.util.spec_from_file_location('w2b1_rules', os.path.join(HERE, 'w2b1_rules.py'))
R = importlib.util.module_from_spec(spec)
spec.loader.exec_module(R)

STEPS = {'C': 0, 'D': 2, 'E': 4, 'F': 5, 'G': 7, 'A': 9, 'B': 11}


def midi(name):
    """'Bb3' -> 58, 'F#3' -> 54 (C4 = 60)."""
    m = re.fullmatch(r'([A-G])(bb|b|##|#)?(-?\d+)', name)
    if not m:
        sys.exit('bad note name ' + name)
    acc = {'': 0, None: 0, 'b': -1, 'bb': -2, '#': 1, '##': 2}[m.group(2)]
    return 12 * (int(m.group(3)) + 1) + STEPS[m.group(1)] + acc


# transpositions (written -> sounding) as the generated wind data has them
TR = {k: int(v) for k, v in re.findall(r'\{ "([^"]+)", \{ (-?\d+), (?:true|false),', open(WINDS_H).read())}

LEVELS = {'any': 'ANY', 'soft': 'SOFT', 'p/mp': 'P_MP', 'fff': 'FFF'}
KINDS = {'warning': 'WARNING', 'red': 'RED', 'note': 'NOTE'}
TOP = 127


def cstr(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


rows = []
for r in R.RULES:
    for i in r['instruments']:
        if i not in TR:
            sys.exit('%s: %s is not in playabilitywinds.h' % (r['id'], i))
    lo = midi(r['lo'])
    hi = midi(r['hi']) if r['hi'] else TOP
    assert lo <= hi, r['id']
    if 'check' in r:
        c = r['check']
        for i in r['instruments']:
            tr = TR[i]
            if c[0] == 'written':
                if (lo - tr, hi - tr) != (midi(c[1]), midi(c[2])):
                    sys.exit('%s: %s written band %d-%d is not %s-%s' % (r['id'], i, lo - tr, hi - tr, c[1], c[2]))
            elif c[0] == 'written below':
                if not hi - tr < midi(c[1]):
                    sys.exit('%s: %s written top %d is not below %s' % (r['id'], i, hi - tr, c[1]))
    assert r['pitch'] in ('sounding', 'written'), r['id']
    rows.append('        { %s, { %s }, %s, %d, %d, WindLevel::%s, WindDynKind::%s,\n          %s,\n          %s },'
                % (cstr(r['id']), ', '.join(cstr(i) for i in r['instruments']),
                   'true' if r['pitch'] == 'written' else 'false', lo, hi,
                   LEVELS[r['level']], KINDS[r['kind']], cstr(r['text']), cstr(r['source'])))

out = '''//=============================================================================
//  MuseScore
//  Music Composition & Notation
//
//  Playability checker: W2 (woodwinds) / B1 (brass) register x dynamic rules.
//  GENERATED by tools/playability/gen_winds_dyn.py from tools/playability/w2b1_rules.py.
//  Do not edit by hand.
//
//  This program is free software; you can redistribute it and/or modify
//  it under the terms of the GNU General Public License version 2
//  as published by the Free Software Foundation and appearing in
//  the file LICENCE.GPL
//=============================================================================

#ifndef __PLAYABILITYWINDSDYN_H__
#define __PLAYABILITYWINDSDYN_H__

#include <vector>

namespace Ms {

// the level a rule needs: any, pp or softer, exactly p or mp, fff or louder
enum class WindLevel { ANY, SOFT, P_MP, FFF };
// a mark (warning / red) with its row, or a note in the panel only
enum class WindDynKind { WARNING, RED, NOTE };

struct WindDynRule {
      const char* id;
      std::vector<const char*> instruments;  // playabilitywinds.h ids
      bool written;                          // lo/hi are written pitches (sounding - WindData::tr)
      int lo, hi;                            // MIDI, both ends included
      WindLevel level;
      WindDynKind kind;
      const char* text;
      const char* source;                    // book and page
      };

inline const std::vector<WindDynRule>& windDynRules()
      {
      static const std::vector<WindDynRule> rules = {
%s
            };
      return rules;
      }

}     // namespace Ms
#endif
''' % '\n'.join(rows)

open(OUT, 'w').write(out)
print('wrote', os.path.normpath(OUT), len(rows), 'rules')
